<?php
/* 
 * Example of a partial view, that you can load in a controller using Zend_View->render method.
 * 
 * NOTE: if you don't need partial views, simply delete the entire 'partials' folder.
 */
?>

<h2>This a help partial view!</h2>
<p>It is possible to load this in other parts of Plesk interface, for example to show a help page somewhere.</p>
<h3>Subtitle</h3>
<p>This is another paragraph of text.</p>
<pre><code>Hello World!</code></pre>
